export const queryKeys = {
  setup: ["setup"] as const,
  setupDatabase: ["setup", "database"] as const,
  me: ["me"] as const,
  userSettings: ["user-settings"] as const,
  home: ["home"] as const,
  favorites: ["favorites"] as const,
  libraries: ["libraries"] as const,
  library: (
    libraryId: string,
    page: number,
    itemTypes?: string,
    sortBy = "Name",
    sortOrder = "Ascending",
    metadataStatus = "all",
  ) => ["library", libraryId, page, itemTypes ?? "root", sortBy, sortOrder, metadataStatus] as const,
  item: (itemId: string) => ["item", itemId] as const,
  itemImages: (itemId: string) => ["item-images", itemId] as const,
  children: (itemId: string, itemType?: string, seasonId?: string) =>
    ["children", itemId, itemType ?? "default", seasonId ?? "all"] as const,
  playback: (itemId: string) => ["playback", itemId] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminHealth: ["admin", "health"] as const,
  adminLibraries: ["admin", "libraries"] as const,
  adminChapterSources: ["admin", "chapter-sources"] as const,
  adminPlugins: ["admin", "plugins"] as const,
  adminPluginStore: ["admin", "plugin-store"] as const,
  adminInstalledPlugins: ["admin", "plugins", "installed"] as const,
  adminUsers: ["admin", "users"] as const,
  adminJobs: (status?: string) => ["admin", "jobs", status ?? "all"] as const,
  adminScheduledTasks: (page = 1) => ["admin", "scheduled-tasks", page] as const,
  adminMetadataJobs: (status?: string) => ["admin", "metadata-jobs", status ?? "all"] as const,
  adminLogs: ["admin", "logs"] as const,
  adminSettings: ["admin", "settings"] as const,
  adminItemImages: (itemId: string) => ["admin", "item-images", itemId] as const,
};

export const queryRefreshIntervals = {
  liveDashboard: 15_000,
  mediaSurface: 15_000,
} as const;
