services:
  lux:
    image: pdzhou/lux:latest
    container_name: lux
    user: "0:0"
    ports:
      - "8097:8097"
    volumes:
      - ./config:/config:rw
      - ./media:/media:rw
    restart: unless-stopped
